openapi: 3.0.0
info:
  version: '1.0.0'
  title: Kytos SDX integration
  description: Kytos NApp for integrate AtlanticWave SDX2.0 Local controller with Kytos OXPO
servers:
  - url: /api/kytos/sdx_topology
paths:
  /v1/l2vpn/:
    get:
      summary: List/Retrieve multiple SDX L2VPNs
      description: List all SDX L2VPN stored
      operationId: list_l2vpn
      parameters:
        - name: archived
          in: query
          schema:
            type: string
          description: "Filter for archived value, if not null. It's false by default"
          required: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/L2VPN'

    post:
      summary: Creates a new L2VPN PTP
      operationId: create_l2vpn_ptp
      requestBody:
        description: Creates a new L2VPN PTP based on the endpoints and
          constraints given.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewL2VPN'
      responses:
        '201':
          description: L2VPN Service Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  service_id:
                    type: string
        '400':
          description: Request does not have a valid JSON or body is incomplete/incorrect
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Not Authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '402':
          description: Request not compatible (For instance, when a L2VPN P2MP is requested but only L2VPN P2P is supported)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: L2VPN Service ID not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: L2VPN Service already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '410':
          description: Can't fulfill the strict QoS requirements
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '411':
          description: Scheduling not possible
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/l2vpn/{service_id}:
    get:
      summary: List/Retrieve one SDX L2VPN
      description: Get the details of a single SDX L2VPN
      operationId: get_l2vpn
      parameters:
        - name: service_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/L2VPN'
        '401':
          description: Not Authorized
        '404':
          description: Service ID not found
    patch:
      summary: Edit/Change a SDX L2VPN
      description: Edit/Change a SDX L2VPN based on payload.
      operationId: update_l2vpn
      parameters:
        - name: service_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Update a SDX L2VPN based on the service_id and payload given
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewL2VPN'
      responses:
        '201':
          description: L2VPN Service Modified
        '400':
          description: Request does not have a valid JSON or body is incomplete
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Not Authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '402':
          description: Request not compatible (For instance, when a L2VPN P2MP is requested but only L2VPN P2P is supported)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: L2VPN Service ID not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Conflicts with a different L2VPN
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '410':
          description: Can't fulfill the strict QoS requirements
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '411':
          description: Scheduling not possible
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete a SDX L2VPN
      description: Delete a SDX L2VPN
      operationId: delete_l2vpn
      parameters:
        - name: service_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: L2VPN Deleted
        '401':
          description: Not Authorized
        '404':
          description: L2VPN Service ID provided does not exist

components:
  schemas:
    NewL2VPN: # Can be referenced via '#/components/schemas/NewL2VPN'
      type: object
      required:
        - name
        - endpoints
      properties:
        name:
          type: string
        endpoints:
          type: array
          items:
            $ref: '#/components/schemas/Endpoint'
        description:
          type: string
        state:
          type: string
          enum:
            - enabled  # the L2VPN is in administrative enable mode
            - disabled  # the L2VPN is in administrative disable mode
        notifications:
          type: array
          items:
            type: object
            properties:
              email:
                type: string
            example:
              email: user@domain.com
        scheduling:
          type: object
          properties:
            start_time:
              type: string
            end_time:
              type: string
        qos_metrics:
          type: object
          properties:
            min_bw:
              type: object
              properties:
                value:
                  type: integer
                  minimum: 0
                  maximum: 100
                strict:
                  type: boolean
            max_delay:
              type: object
              properties:
                value:
                  type: integer
                  minimum: 0
                  maximum: 1000
                strict:
                  type: boolean

    Endpoint: # Can be referenced via '#/components/schemas/Endpoint'
      type: object
      required:
        - port_id
        - vlan
      properties:
        port_uri:
          type: string
        vlan:
          type: string
          pattern: '^(any|untagged|all|[0-9]+:[0-9]+|[0-9]+)$'

    L2VPN: # Can be referenced via '#/components/schemas/L2VPN'
      allOf:
        - $ref: '#/components/schemas/NewL2VPN'
      properties:
        service_id:
          type: string
        creation_date:
          type: string
        archived_date:
          type: string
        status:
          type: string
          enum:
            - up  # the L2VPN is operational
            - down  # the L2VPN is not operational due to topology issues/lack of path or endpoints being down
            - error  # when there is an error with the L2VPN
            - under provisioning  # when the L2VPN is still being provisioned by the OXPs
            - maintenance  # when the L2VPN is being affected by a network maintenance
        counters_location:
          type: string
        last_modified:
          type: string

    Error: # Can be referenced via '#/components/schemas/Error'
      type: object
      properties:
        code:
          type: integer
        description:
          type: string
      required:
        - code
        - description
