# Run some code checks with GitHub Actions.

name: Code checks

on:
  push:
    branches:
      - "main"
  pull_request:

permissions:
  contents: read

jobs:

  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Check out sources
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Tox
        run: |
          pip install tox==4.13.0 virtualenv==20.25.1 pip==24.3.1 setuptools==75.6.0 wheel==0.45.1 coverage

      - name: Lint
        run: |
          # run only linter
          tox -e lint

      - name: Lint kytos-sdx Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

